### ISSUE TITLE
Graphic glitch with Podcastlogo before episode title

### ISSUE THREAD

**Issue by peperjohnny** [gpodder/gpodder-sailfish#125]
There's a minor glitch with the new feature of showing the Podcastlogo before the episode.
Normally it should show only once, but it shows next to the length and subinfo of the episode too.
[Here's a pic of how it looks.](https://nc.peperjohnny.org/s/cmGtZpCXQRgcZ9G)
[Here's how it looks on the filtered view.](https://nc.peperjohnny.org/s/72DzdZrbgjg7iBR)
As far as I can tell it happens only on new downloaded episodes. And on Podcasts where I newly downloaded an episode. This issue persists through a restart of the app. Funnily enough it does not happen to every Podcast or episode, so far for 2 of newly downloaded I had the glitch and for one not.
If you need any logs, please tell which and I will provide them gladly.

**Comment by Keeper-of-the-Keys** [comment]
This is due to the podcast stream using the podcast cover as episode art, basically I download both cover_art and episode_art if both exist you have the 2 pictures if only one exists it shows just 1 picture.

I don't have a trustworthy mechanism to check if both are the same (sometimes it's the same file but sometimes it's not), I guess I could add at least a "same filename" rule to prevent this in that case (I could also compare/hash the files but that would undoubtedly tank performance).

**Comment by Keeper-of-the-Keys** [comment]
(Do you use nextcloud as e-mail frontend? I'm thinking about using it)

**Comment by peperjohnny** [comment]
I guess I could live with that, because it's really not a big bother.
(Nope. Using it for a variety of different things, but since I have mail clients on every device, I haven't seen any advantage in having it in there too.)

**Comment by Keeper-of-the-Keys** [comment]
This was resolved I think by the removal of episode art from episode lists (for performance/memory reasons).
