### ISSUE TITLE
Uninstalling does not remove data

### ISSUE THREAD

**Issue by thigg** [gpodder/gpodder-sailfish#154]
Uninstalling the app does not remove the local data

**Comment by Keeper-of-the-Keys** [comment]
I don't think it should, user data needs to be removed by the user.

A user may uninstall because they want to reinstall (for whatever reason) without having to readd / redownload everything.

On a Linux desktop uninstalling Firefox also does not remove the .mozilla/firefox folder or it's contents.

We can provide a simple script or instructions on removing user data but that should definitely not be a default action.

**Comment by sfbg** [comment]
Fully agree with @Keeper-of-the-Keys, this is standard behaviour.
