### ISSUE TITLE
gPodder does not consider custom "Section Headers" when exporting/importing OPML Files

### ISSUE THREAD

**Issue by EarthlingX** [gpodder/gpodder-sailfish#165]
Dear Keeper-of-the-Keys,

I hope you are doing fine! Since your great suggestion of [using custom section headers](https://github.com/gpodder/gpodder-sailfish/issues/164#issuecomment-1008164691) to get some structure into my podcast playlist I am very fascinated about this nice feature!

Unfortunately custom sections neither will get considered when exporting my playlist as an OPML file nor get considered when re-importing the OPML-file again. It seems that custom sections are just missing completely within the OPML file import/export functionality.

Would it be a huge effort to adjust this behavior, so that also section headers will get considered within OPML-files?

Please let me know if I can send you some financial obulus for that. :+1: 

Thank you very much in advance!

**Comment by Keeper-of-the-Keys** [comment]
Hey minor update - 
As far as I can tell "official" OPML does not currently support sections, I have opened a ticket with the managers of that standard to see if it can be expanded so that OPML files generated by gPodder will be handled properly by anyone who implements the spec.

In the mean time I am probably going to try to adjust the opml code to support this feature.

If you want to follow the issue it can be found here:
https://github.com/scripting/opml.org/issues/15

Sorry about the long delay.

**Comment by Keeper-of-the-Keys** [comment]
I just added export with section headers, now starting to test import, should be in the next release.
