### ISSUE TITLE
4.13.0 hangs when the Play button is pressed

### ISSUE THREAD

**Issue by sfbg** [gpodder/gpodder-sailfish#174]
What the title says. When the Play button is pressed, the whole app immediately hangs and Sailfish asks to wait or close it. Playback does not start.

**Comment by Keeper-of-the-Keys** [comment]
Hey, which one of the play buttons? Cover? player? dropdown menu?

For me this does not happen, but the app as a whole sometimes hangs on pulldown menu however it always seemed to me that these lockups on "basic" tasks were at the OS level (because generally other apps also misbehave similarly at that time) and usually resolve with a reboot of the phone.
