### ISSUE TITLE
Memory usage slowly grows

### ISSUE THREAD

**Issue by salyavin** [gpodder/gpodder-sailfish#30]
I often have sailtime open to see how tight I am on memory.  It appears to me gpodder slowly grows in memory usage after a day or 2 of fairly heavy use gpodder becomes very slow to respond.  If I close gpodder and reopen it I regain speed and memory.

**Comment by Keeper-of-the-Keys** [comment]
Hey @salyavin 
Many releases of gPodder have happened since your bug report, so far I have not experienced something similar on the versions I ran so I'm going to close the issue.
Should this still happen with new versions please don't hesitate to open a new issue.
Thanks and sorry it took a while!
(I took over last summer and between fixing new issues and adding new features I'm trying to also go over the old ones)
